# Generated by Django 5.2.11 on 2026-02-21 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemName",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="품목명",
                    ),
                ),
            ],
            options={
                "verbose_name": "품목명",
                "verbose_name_plural": "품목 관리",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseSupplier",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="출고처명",
                    ),
                ),
            ],
            options={
                "verbose_name": "출고처",
                "verbose_name_plural": "출고처 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="입고처명",
                    ),
                ),
            ],
            options={
                "verbose_name": "입고처",
                "verbose_name_plural": "입고처 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="관리 고유번호",
                    ),
                ),
                ("date", models.DateField(verbose_name="입고일 자")),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="시리얼 번호",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="출고일자"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("재고", "재고 (입고됨)"), ("출고", "출고 완료")],
                        default="재고",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="tool_inventory.itemname",
                        verbose_name="품목명",
                    ),
                ),
                (
                    "release_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tool_inventory.releasesupplier",
                        verbose_name="출고처",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="tool_inventory.supplier",
                        verbose_name="입고처",
                    ),
                ),
            ],
            options={
                "verbose_name": "툴/장비 인벤토리",
                "verbose_name_plural": "툴/장비 인벤토리 관리",
                "ordering": ["-date"],
            },
        ),
    ]
