# Generated by Django 5.2.11 on 2026-02-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundInventory",
            fields=[],
            options={
                "verbose_name": "개별 입고 내역",
                "verbose_name_plural": "개별 입고 내역",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tool_inventory.inventory",),
        ),
        migrations.CreateModel(
            name="OutboundInventory",
            fields=[],
            options={
                "verbose_name": "출고 등록",
                "verbose_name_plural": "출고 등록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tool_inventory.inventory",),
        ),
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inbound_date", models.DateField(verbose_name="입고 날짜")),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당자/부서"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_batches",
                        to="tool_inventory.supplier",
                        verbose_name="입고업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "입고 배치",
                "verbose_name_plural": "입고 등록",
                "ordering": ["-inbound_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="tool_inventory.inventorybatch",
                verbose_name="입고 배치",
            ),
        ),
    ]
