# Generated by Django 5.2.11 on 2026-02-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        (
            "tool_inventory",
            "0002_inboundinventory_outboundinventory_inventorybatch_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="as_release_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="as_app.company",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="as_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.outsourcecompany",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="as_tool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.tool",
            ),
        ),
        migrations.AddField(
            model_name="inventorybatch",
            name="as_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.outsourcecompany",
                verbose_name="입고처(AS앱)",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tool_inventory.itemname",
                verbose_name="품목명",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tool_inventory.supplier",
                verbose_name="입고처",
            ),
        ),
        migrations.AlterField(
            model_name="inventorybatch",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_batches",
                to="tool_inventory.supplier",
                verbose_name="입고업체",
            ),
        ),
    ]
