# Generated by Django 5.2.11 on 2026-02-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tool_inventory",
            "0003_inventory_as_release_company_inventory_as_supplier_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name='inventory', name='name'),
        migrations.RemoveField(model_name='inventory', name='supplier'),
        migrations.RemoveField(model_name='inventory', name='release_supplier'),
        migrations.RemoveField(model_name='inventorybatch', name='supplier'),
        migrations.DeleteModel(name='ItemName'),
        migrations.DeleteModel(name='Supplier'),
        migrations.DeleteModel(name='ReleaseSupplier'),
        migrations.RenameField(model_name='inventory', old_name='as_supplier', new_name='supplier'),
        migrations.RenameField(model_name='inventory', old_name='as_tool', new_name='tool'),
        migrations.RenameField(model_name='inventory', old_name='as_release_company', new_name='release_company'),
        migrations.RenameField(model_name='inventorybatch', old_name='as_supplier', new_name='supplier'),
    ]
