# Generated by Django 5.2.11 on 2026-02-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        ("tool_inventory", "0004_finalize_mapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorybatch",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="inventorybatch",
            name="memo",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="release_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="as_app.company",
                verbose_name="출고처",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.outsourcecompany",
                verbose_name="입고처",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="tool",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.tool",
                verbose_name="품목명",
            ),
        ),
        migrations.AlterField(
            model_name="inventorybatch",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_batches",
                to="as_app.outsourcecompany",
                verbose_name="입고업체",
            ),
        ),
    ]
