# Generated by Django 5.2.11 on 2026-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tool_inventory",
            "0006_alter_inventory_supplier_alter_inventory_tool_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[("재고", "재고"), ("출고", "출고 완료")],
                default="재고",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
