# Generated by Django 5.2.11 on 2026-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_inventory", "0007_alter_inventory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[("재고", "재고"), ("출고", "출고")],
                default="재고",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
