# Generated by Django 5.2.11 on 2026-02-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        ("tool_inventory", "0008_alter_inventory_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="출고 날짜")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "release_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_outbound_batches",
                        to="as_app.company",
                        verbose_name="출고업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "일괄 출고 등록",
                "verbose_name_plural": "일괄 출고 등록",
                "ordering": ["-release_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboundTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tool_inventory.outboundbatch",
                        verbose_name="출고 배치",
                    ),
                ),
                (
                    "inventory",
                    models.OneToOneField(
                        limit_choices_to={"status": "재고"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tool_inventory.inventory",
                        verbose_name="대상 장비 (시리얼)",
                    ),
                ),
            ],
            options={
                "verbose_name": "출고등록 티켓",
                "verbose_name_plural": "출고등록 티켓",
            },
        ),
    ]
