# Generated by Django 5.2.11 on 2026-02-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        ("tool_inventory", "0009_outboundbatch_outboundticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboundticket",
            name="inventory",
        ),
        migrations.AddField(
            model_name="outboundticket",
            name="inventories",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"status": "재고"},
                to="tool_inventory.inventory",
                verbose_name="출고 대상 (시리얼 다중선택)",
            ),
        ),
        migrations.AddField(
            model_name="outboundticket",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="시리얼 미선택 시, 이 수량만큼 선입선출 출고",
                verbose_name="출고 수량",
            ),
        ),
        migrations.AddField(
            model_name="outboundticket",
            name="tool",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.tool",
                verbose_name="대상 장비",
            ),
            preserve_default=False,
        ),
    ]
