# Generated by Django 5.2.11 on 2026-02-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        ("tool_inventory", "0010_remove_outboundticket_inventory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-date"],
                "verbose_name": "통합 재고 리스트",
                "verbose_name_plural": "통합 재고 리스트",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorybatch",
            options={
                "ordering": ["-inbound_date", "-created_at"],
                "verbose_name": "입고 등록",
                "verbose_name_plural": "입고 등록",
            },
        ),
        migrations.AlterModelOptions(
            name="outboundbatch",
            options={
                "ordering": ["-release_date", "-created_at"],
                "verbose_name": "출고 등록",
                "verbose_name_plural": "출고 등록",
            },
        ),
        migrations.AlterField(
            model_name="outboundticket",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="as_app.tool",
                verbose_name="품목",
            ),
        ),
    ]
