# Generated by Django 5.2.11 on 2026-02-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
        (
            "tool_inventory",
            "0011_alter_inventory_options_alter_inventorybatch_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolStockSummary",
            fields=[],
            options={
                "verbose_name": "재고 현황",
                "verbose_name_plural": "재고",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.tool",),
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-date"],
                "verbose_name": "통합 입출고 이력",
                "verbose_name_plural": "통합 입출고 이력",
            },
        ),
    ]
