# Generated by Django 5.2.11 on 2026-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_inventory", "0012_toolstocksummary_alter_inventory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="할 일")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "할 일",
                "verbose_name_plural": "할 일 목록",
                "ordering": ["is_done", "-created_at"],
            },
        ),
    ]
