# Generated by Django 5.2.11 on 2026-03-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_inventory", "0013_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventories",
                to="tool_inventory.inventorybatch",
                verbose_name="입고 배치",
            ),
        ),
    ]
