# Generated by Django 5.2.11 on 2026-03-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool_inventory", "0015_update_fk_to_master_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-date", "tool__model_name"],
                "verbose_name": "통합 입출고 이력",
                "verbose_name_plural": "통합 입출고 이력",
            },
        ),
        migrations.AlterModelOptions(
            name="toolstocksummary",
            options={"verbose_name": "재고 현황", "verbose_name_plural": "재고"},
        ),
        migrations.AddField(
            model_name="inventory",
            name="usage_process",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="적용공정/용도"
            ),
        ),
        migrations.AddField(
            model_name="outboundticket",
            name="usage_process",
            field=models.CharField(
                blank=True,
                help_text="[선택] 출고 시 현장 적용 공정이나 용도를 기입",
                max_length=50,
                null=True,
                verbose_name="적용공정/용도",
            ),
        ),
    ]
