"""
Django settings for as_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v$k4h61pw&f^1de0c%f^6&(x354qmo@-lq0wdyjt$o9-n1x#m3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "as_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "as_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "as_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────
# Django Unfold 설정
# ──────────────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "AS 관리 시스템",
    "SITE_HEADER": "AS 관리 시스템",
    "SITE_SYMBOL": "build",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "AS 관리",
                "separator": True,
                "items": [
                    {
                        "title": "입고 등록",
                        "icon": "inbox",
                        "link": reverse_lazy("admin:as_app_inboundbatch_add"),
                    },
                    {
                        "title": "수리 기록",
                        "icon": "build",
                        "link": reverse_lazy("admin:as_app_repairticket_changelist"),
                    },
                    {
                        "title": "출고 처리",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:as_app_outboundticket_changelist"),
                    },
                    {
                        "title": "통합 이력",
                        "icon": "history",
                        "link": reverse_lazy("admin:as_app_ashistory_changelist"),
                    },
                ],
            },
            {
                "title": "기준 정보",
                "separator": True,
                "items": [
                    {
                        "title": "업체 관리",
                        "icon": "business",
                        "link": reverse_lazy("admin:as_app_company_changelist"),
                    },
                    {
                        "title": "브랜드 & 툴 관리",
                        "icon": "hardware",
                        "link": reverse_lazy("admin:as_app_tool_changelist"),
                    },
                    {
                        "title": "부품 관리",
                        "icon": "settings",
                        "link": reverse_lazy("admin:as_app_part_changelist"),
                    },
                ],
            },
        ],
    },
}
