"""
Django settings for as_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-v$k4h61pw&f^1de0c%f^6&(x354qmo@-lq0wdyjt$o9-n1x#m3")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "simple_history",
    "master_data",
    "as_app",
    "tool_inventory",
    "hr_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "as_project.urls"

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://*.trycloudflare.com",
    "https://*.loca.lt",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "as_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgres://postgres:123456@localhost:5433/as_project_db",
        conn_max_age=600,
    )
}


# ──────────────────────────────────────────────
# 인증 백엔드 (작업자 이상 = 전체 업무 권한 자동 부여)
# ──────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    "as_project.backends.StaffFullAccessBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────
# Django Unfold 설정
# ──────────────────────────────────────────────
from unfold.sites import UnfoldAdminSite

def dashboard_callback(request, context):
    if request.path.startswith('/inventory/'):
        from tool_inventory.dashboard import dashboard_callback as inv_callback
        return inv_callback(request, context)
    elif request.path.startswith('/sysadmin/'):
        return context
    elif request.path.startswith('/hr/'):
        return context
    elif request.path.startswith('/master/'):
        return context
    else:
        from as_app.dashboard import dashboard_callback as as_callback
        return as_callback(request, context)

def sidebar_callback(request):
    if request.path.startswith('/inventory/'):
        return [
            {
                "title": "내비게이션",
                "separator": False,
                "items": [
                    {
                        "title": "포탈로 돌아가기",
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "대시보드",
                "separator": True,
                "items": [
                    {
                        "title": "대시보드",
                        "icon": "dashboard",
                        "link": reverse_lazy("tool_admin:index"),
                    },
                ],
            },
            {
                "title": "툴 입출고 관리",
                "separator": True,
                "items": [
                    {
                        "title": "통합 입출고 이력",
                        "icon": "history",
                        "link": reverse_lazy("tool_admin:tool_inventory_inventory_changelist"),
                    },
                    {
                        "title": "입고 등록",
                        "icon": "inbox",
                        "link": reverse_lazy("tool_admin:tool_inventory_inventorybatch_add"),
                    },
                    {
                        "title": "출고 등록",
                        "icon": "local_shipping",
                        "link": reverse_lazy("tool_admin:tool_inventory_outboundbatch_add"),
                    },
                ],
            },
            {
                "title": "재고",
                "separator": True,
                "items": [
                    {
                        "title": "재고",
                        "icon": "inventory_2",
                        "link": reverse_lazy("tool_admin:tool_inventory_toolstocksummary_changelist"),
                    },
                ],
            },
            {
                "title": "기준 정보",
                "separator": True,
                "items": [
                    {
                        "title": "매출처",
                        "icon": "local_shipping",
                        "link": reverse_lazy("master_data_admin:master_data_company_changelist"),
                    },
                    {
                        "title": "입고업체",
                        "icon": "store",
                        "link": reverse_lazy("master_data_admin:master_data_outsourcecompany_changelist"),
                    },
                    {
                        "title": "브랜드/툴 관리",
                        "icon": "category",
                        "link": reverse_lazy("master_data_admin:master_data_tool_changelist"),
                    },
                ],
            },
        ]
    elif request.path.startswith('/sysadmin/'):
        return [
            {
                "title": "내비게이션",
                "separator": False,
                "items": [
                    {
                        "title": "포탈로 돌아가기",
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "시스템 계정 관리",
                "separator": True,
                "items": [
                    {
                        "title": "사용자(회원) 관리",
                        "icon": "person",
                        "link": reverse_lazy("sysadmin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": "활동 모니터링",
                "separator": True,
                "items": [
                    {
                        "title": "전체 활동 기록",
                        "icon": "history",
                        "link": reverse_lazy("sysadmin:admin_logentry_changelist"),
                    },
                ],
            },
        ]
    elif request.path.startswith('/hr/'):
        return [
            {
                "title": "내비게이션",
                "separator": False,
                "items": [
                    {
                        "title": "포탈로 돌아가기",
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "근무 현황판",
                "separator": True,
                "items": [
                    {
                        "title": "내 근무 달력",
                        "icon": "calendar_month",
                        "link": reverse_lazy("hr_admin:index"), 
                    },
                ],
            },
            {
                "title": "근태 데이터 관리",
                "separator": True,
                "items": [
                    {
                        "title": "근태 기록 목록",
                        "icon": "list_alt",
                        "link": reverse_lazy("hr_admin:hr_app_attendancerecord_changelist"),
                    },
                ],
            },
        ]
    elif request.path.startswith('/master/'):
        return [
            {
                "title": "내비게이션",
                "separator": False,
                "items": [
                    {
                        "title": "포탈로 돌아가기",
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "업체 관리",
                "separator": True,
                "items": [
                    {
                        "title": "매출처",
                        "icon": "business",
                        "link": reverse_lazy("master_data_admin:master_data_company_changelist"),
                    },
                    {
                        "title": "의뢰업체",
                        "icon": "handshake",
                        "link": reverse_lazy("master_data_admin:master_data_outsourcecompany_changelist"),
                    },
                    {
                        "title": "단가 그룹",
                        "icon": "sell",
                        "link": reverse_lazy("master_data_admin:master_data_companycategory_changelist"),
                    },
                ],
            },
            {
                "title": "장비 관리",
                "separator": True,
                "items": [
                    {
                        "title": "브랜드 & 툴",
                        "icon": "hardware",
                        "link": reverse_lazy("master_data_admin:master_data_tool_changelist"),
                    },
                ],
            },
        ]
    else:
        return [
            {
                "title": "내비게이션",
                "separator": False,
                "items": [
                    {
                        "title": "포탈로 돌아가기",
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "대시보드",
                "separator": True,
                "items": [
                    {
                        "title": "대시보드",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "AS 관리",
                "separator": True,
                "items": [
                    {
                        "title": "통합 이력",
                        "icon": "history",
                        "link": reverse_lazy("admin:as_app_ashistory_changelist"),
                    },
                ],
            },
            {
                "title": "AS 등록",
                "separator": True,
                "items": [
                    {
                        "title": "입고 등록",
                        "icon": "inbox",
                        "link": reverse_lazy("admin:as_app_inboundbatch_add"),
                    },
                    {
                        "title": "수리 의뢰 등록",
                        "icon": "send",
                        "link": reverse_lazy("admin:as_app_outsourcedticket_changelist"),
                    },
                    {
                        "title": "수리 기록 등록",
                        "icon": "build",
                        "link": reverse_lazy("admin:as_app_repairticket_changelist"),
                    },
                    {
                        "title": "출고 등록",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:as_app_outboundticket_changelist"),
                    },
                    {
                        "title": "세금계산서 등록",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:as_app_taxinvoiceticket_changelist"),
                    },
                ],
            },
            {
                "title": "추출",
                "separator": True,
                "items": [
                    {
                        "title": "견적서 발행 (데모)",
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:as_app_estimateticket_changelist"),
                    },
                ],
            },
            {
                "title": "기준 정보",
                "separator": True,
                "items": [
                    {
                        "title": "업체관리",
                        "icon": "business",
                        "link": reverse_lazy("admin:master_data_company_changelist"),
                    },
                    {
                        "title": "수리부품 관리",
                        "icon": "settings",
                        "link": reverse_lazy("admin:as_app_part_changelist"),
                    },
                    {
                        "title": "브랜드 & 툴 관리",
                        "icon": "hardware",
                        "link": reverse_lazy("admin:master_data_tool_changelist"),
                    },
                ],
            },
        ]


def site_title_callback(request):
    if request.path.startswith('/inventory/'):
        return "장비/툴 관리"
    elif request.path.startswith('/sysadmin/'):
        return "시스템 관리"
    elif request.path.startswith('/hr/'):
        return "근무/근태 관리"
    elif request.path.startswith('/master/'):
        return "기준정보 관리"
    return "AS 관리"

def site_header_callback(request):
    if request.path.startswith('/inventory/'):
        return "툴 입출고 관리"
    elif request.path.startswith('/sysadmin/'):
        return "시스템 권한 승인 센터"
    elif request.path.startswith('/hr/'):
        return "근무 관리 포털"
    elif request.path.startswith('/master/'):
        return "기준정보 관리 포털"
    return "AS 시스템"

def site_symbol_callback(request):
    if request.path.startswith('/inventory/'):
        return "inventory_2"
    elif request.path.startswith('/sysadmin/'):
        return "admin_panel_settings"
    elif request.path.startswith('/hr/'):
        return "event_available"
    elif request.path.startswith('/master/'):
        return "database"
    return "build"

UNFOLD = {
    "SITE_TITLE": "as_project.settings.site_title_callback",
    "SITE_HEADER": "as_project.settings.site_header_callback",
    "SITE_SYMBOL": "as_project.settings.site_symbol_callback",
    "DASHBOARD_CALLBACK": "as_project.settings.dashboard_callback",
    "STYLES": [
        lambda request: static("as_app/css/mobile_fix.css"),
    ],
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": "as_project.settings.sidebar_callback",
    },
}
