# Generated by Django 5.2.11 on 2026-02-23 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="근무 일자"
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "정상근무"),
                            ("OVERTIME", "연장근무"),
                            ("WEEKEND", "주말특근"),
                            ("LEAVE_FULL", "연차 (종일)"),
                            ("LEAVE_HALF_AM", "오전반차"),
                            ("LEAVE_HALF_PM", "오후반차"),
                            ("SICK_LEAVE", "병가"),
                            ("PUBLIC_LEAVE", "공가"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="근무 형태",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="예: 09:00:00",
                        null=True,
                        verbose_name="시작 시간",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="예: 18:00:00",
                        null=True,
                        verbose_name="종료 시간",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="추가 근무한 시간 (단위: 시간)",
                        max_digits=4,
                        verbose_name="연장/특근 시간(H)",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="예: 주말 장비 셋업, 병원 진료 등",
                        verbose_name="근무/휴가 메모",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="직원",
                    ),
                ),
            ],
            options={
                "verbose_name": "근태 기록",
                "verbose_name_plural": "근태 기록 목록",
                "ordering": ["-date", "user"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
