# Generated by Django 5.2.11 on 2026-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="estimate_company_name",
            field=models.CharField(
                blank=True,
                help_text="견적서에 표시될 업체 이름을 입력하세요. 미설정 시 견적서 발행이 차단됩니다.",
                max_length=200,
                null=True,
                verbose_name="견적서용 업체명",
            ),
        ),
    ]
