# Generated by Django 5.2.11 on 2026-02-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ASTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inbound_date", models.DateField(verbose_name="입고 날짜")),
                (
                    "manager",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=200, verbose_name="시리얼 번호"),
                ),
                (
                    "symptom",
                    models.TextField(blank=True, verbose_name="요청사항 및 증상"),
                ),
                (
                    "repair_content",
                    models.TextField(blank=True, verbose_name="AS 내용 (수리 내역)"),
                ),
                (
                    "repair_cost",
                    models.PositiveIntegerField(default=0, verbose_name="AS 비용"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inbound", "입고"),
                            ("repairing", "수리중"),
                            ("repaired", "수리완료"),
                            ("shipped", "출고"),
                        ],
                        default="inbound",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "outbound_date",
                    models.DateField(blank=True, null=True, verbose_name="출고 날짜"),
                ),
                (
                    "estimate_status",
                    models.BooleanField(default=False, verbose_name="견적서 추출"),
                ),
                (
                    "tax_invoice",
                    models.BooleanField(default=False, verbose_name="세금계산서 발행"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "AS 티켓",
                "verbose_name_plural": "AS 티켓",
                "ordering": ["-inbound_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="브랜드명"
                    ),
                ),
            ],
            options={
                "verbose_name": "브랜드",
                "verbose_name_plural": "브랜드 관리",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="업체명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "매출처"),
                            ("client", "의뢰처"),
                            ("both", "매출처/의뢰처"),
                        ],
                        default="client",
                        max_length=10,
                        verbose_name="구분",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당자명"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="연락처"),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
            ],
            options={
                "verbose_name": "업체",
                "verbose_name_plural": "업체 관리",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="부품명")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="부품코드"
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="단가")),
                (
                    "part_type",
                    models.CharField(
                        choices=[("dedicated", "전용"), ("common", "공용")],
                        default="dedicated",
                        max_length=10,
                        verbose_name="구분",
                    ),
                ),
            ],
            options={
                "verbose_name": "부품",
                "verbose_name_plural": "부품 관리",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ASHistory",
            fields=[],
            options={
                "verbose_name": "AS 이력",
                "verbose_name_plural": "통합 이력",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.CreateModel(
            name="InboundTicket",
            fields=[],
            options={
                "verbose_name": "입고 등록",
                "verbose_name_plural": "입고 등록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.CreateModel(
            name="OutboundTicket",
            fields=[],
            options={
                "verbose_name": "출고 처리",
                "verbose_name_plural": "출고 처리",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.CreateModel(
            name="RepairTicket",
            fields=[],
            options={
                "verbose_name": "수리 기록",
                "verbose_name_plural": "수리 기록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.AddField(
            model_name="asticket",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="as_app.company",
                verbose_name="업체",
            ),
        ),
        migrations.AddField(
            model_name="asticket",
            name="used_parts",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets",
                to="as_app.part",
                verbose_name="사용 부품",
            ),
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=200, verbose_name="모델명")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="카테고리"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tools",
                        to="as_app.brand",
                        verbose_name="브랜드",
                    ),
                ),
            ],
            options={
                "verbose_name": "장비/툴",
                "verbose_name_plural": "툴 관리",
                "ordering": ["brand__name", "model_name"],
                "unique_together": {("brand", "model_name")},
            },
        ),
        migrations.AddField(
            model_name="part",
            name="tool",
            field=models.ForeignKey(
                blank=True,
                help_text="공용 부품인 경우 비워두세요.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to="as_app.tool",
                verbose_name="장비/툴",
            ),
        ),
        migrations.AddField(
            model_name="asticket",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="as_app.tool",
                verbose_name="장비/툴",
            ),
        ),
    ]
