# Generated by Django 5.2.11 on 2026-02-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="카테고리명"
                    ),
                ),
            ],
            options={
                "verbose_name": "업체 카테고리",
                "verbose_name_plural": "업체 카테고리",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name", "branch"],
                "verbose_name": "업체",
                "verbose_name_plural": "업체 관리",
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="category",
        ),
        migrations.RemoveField(
            model_name="part",
            name="tool",
        ),
        migrations.AddField(
            model_name="company",
            name="branch",
            field=models.CharField(
                blank=True,
                help_text="동일 업체의 다른 법인/지사인 경우 구분용",
                max_length=200,
                verbose_name="법인/지사명",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("sales", "매출처"),
                    ("client", "의뢰처"),
                    ("both", "매출처/의뢰처"),
                ],
                default="client",
                max_length=10,
                verbose_name="업체 구분",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="예: 한국, 일본, 중국, 미국 등",
                max_length=100,
                verbose_name="지역/국가",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="이 부품이 사용되는 장비를 선택하세요. 공용 부품은 여러 장비를 선택할 수 있습니다.",
                related_name="parts",
                to="as_app.tool",
                verbose_name="적용 장비/툴",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_category",
            field=models.ForeignKey(
                blank=True,
                help_text="해외법인, 국내, 대리점 등",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="as_app.companycategory",
                verbose_name="업체 카테고리",
            ),
        ),
    ]
