# Generated by Django 5.2.11 on 2026-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0002_companycategory_alter_company_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="category",
        ),
    ]
