# Generated by Django 5.2.11 on 2026-02-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0003_remove_tool_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inbound_date", models.DateField(verbose_name="입고 날짜")),
                (
                    "manager",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="이번 입고 건에 대한 참고 메모",
                        verbose_name="메모",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_batches",
                        to="as_app.company",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "입고 배치",
                "verbose_name_plural": "입고 등록",
                "ordering": ["-inbound_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="asticket",
            name="inbound_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="as_app.inboundbatch",
                verbose_name="입고 배치",
            ),
        ),
    ]
