# Generated by Django 5.2.11 on 2026-02-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0004_inboundbatch_asticket_inbound_batch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "업체",
                "verbose_name_plural": "업체 관리",
            },
        ),
        migrations.AlterModelOptions(
            name="companycategory",
            options={
                "ordering": ["name"],
                "verbose_name": "단가 그룹",
                "verbose_name_plural": "단가 그룹",
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_category",
        ),
        migrations.RemoveField(
            model_name="company",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
        migrations.AddField(
            model_name="company",
            name="price_group",
            field=models.ForeignKey(
                blank=True,
                help_text="견적서 금액이 다르게 적용되는 그룹",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="as_app.companycategory",
                verbose_name="단가 그룹",
            ),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="단가 그룹명"
            ),
        ),
    ]
