# Generated by Django 5.2.11 on 2026-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0005_alter_company_options_alter_companycategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "입고"),
                    ("waiting", "수리대기"),
                    ("repaired", "수리완료"),
                    ("shipped", "출고"),
                ],
                default="inbound",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
