# Generated by Django 5.2.11 on 2026-02-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0006_alter_asticket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutsourceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="의뢰업체명"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=100, verbose_name="연락처"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
            ],
            options={
                "verbose_name": "의뢰업체",
                "verbose_name_plural": "의뢰업체 관리",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="asticket",
            name="manager",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="담당자/부서"
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="repair_cost",
            field=models.PositiveIntegerField(
                default=0,
                help_text="사용 부품/공임 단가 합산 (자동 계산)",
                verbose_name="AS 비용",
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "입고"),
                    ("waiting", "수리대기"),
                    ("outsourced", "수리의뢰"),
                    ("repaired", "수리완료"),
                    ("shipped", "출고"),
                    ("disposed", "자체폐기"),
                ],
                default="inbound",
                max_length=15,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="used_parts",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets",
                to="as_app.part",
                verbose_name="사용 부품/공임",
            ),
        ),
        migrations.AlterField(
            model_name="inboundbatch",
            name="manager",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="담당자/부서"
            ),
        ),
        migrations.AddField(
            model_name="asticket",
            name="outsource_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="as_app.outsourcecompany",
                verbose_name="의뢰업체",
            ),
        ),
    ]
