# Generated by Django 5.2.11 on 2026-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0007_outsourcecompany_alter_asticket_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_type",
            field=models.CharField(
                choices=[("dedicated", "전용"), ("common", "공용"), ("labor", "공임")],
                default="dedicated",
                max_length=10,
                verbose_name="구분",
            ),
        ),
    ]
