# Generated by Django 5.2.11 on 2026-02-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0009_alter_asticket_repair_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': '매출처', 'verbose_name_plural': '매출처 관리'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
