# Generated by Django 5.2.11 on 2026-02-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0010_remove_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='as_app.company', verbose_name='매출처'),
        ),
        migrations.AlterField(
            model_name='inboundbatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_batches', to='as_app.company', verbose_name='매출처'),
        ),
    ]
