# Generated by Django 5.2.11 on 2026-02-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0013_repairpreset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboundticket",
            options={"verbose_name": "출고 등록", "verbose_name_plural": "출고 등록"},
        ),
        migrations.AlterModelOptions(
            name="repairticket",
            options={
                "verbose_name": "수리 기록 등록",
                "verbose_name_plural": "수리 기록 등록",
            },
        ),
        migrations.AlterModelOptions(
            name="tool",
            options={
                "ordering": ["brand__name", "model_name"],
                "verbose_name": "장비/툴",
                "verbose_name_plural": "브랜드 & 툴 관리",
            },
        ),
    ]
