# Generated by Django 5.2.11 on 2026-02-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0014_alter_outboundticket_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateTicket",
            fields=[],
            options={
                "verbose_name": "견적서 발행 (데모)",
                "verbose_name_plural": "견적서 발행 (데모)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
    ]
