# Generated by Django 5.2.11 on 2026-02-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0015_estimateticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxInvoiceTicket",
            fields=[],
            options={
                "verbose_name": "세금계산서 등록",
                "verbose_name_plural": "세금계산서 등록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
    ]
