# Generated by Django 5.2.11 on 2026-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0016_taxinvoiceticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "입고"),
                    ("repaired", "수리완료"),
                    ("shipped", "출고"),
                    ("disposed", "자체폐기"),
                ],
                default="inbound",
                max_length=15,
                verbose_name="상태",
            ),
        ),
    ]
