# Generated by Django 5.2.11 on 2026-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0017_alter_asticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="part_type",
        ),
        migrations.AddField(
            model_name="part",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="비고"),
        ),
    ]
