# Generated by Django 5.2.11 on 2026-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0019_part_brand_repairpreset_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="region",
        ),
        migrations.AddField(
            model_name="company",
            name="business_category",
            field=models.CharField(
                default="-",
                help_text="예: 산업용 공구, 기계부품 등",
                max_length=100,
                verbose_name="종목",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="business_number",
            field=models.CharField(
                default="-",
                help_text="예: 123-45-67890",
                max_length=20,
                verbose_name="사업자등록번호",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="business_type",
            field=models.CharField(
                default="-",
                help_text="예: 제조업, 도소매업 등",
                max_length=100,
                verbose_name="업태",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="견적서 발송용 이메일",
                max_length=200,
                verbose_name="이메일",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="fax",
            field=models.CharField(
                blank=True,
                help_text="예: 02-1234-5679",
                max_length=30,
                verbose_name="팩스번호",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                default="-",
                help_text="예: 02-1234-5678",
                max_length=30,
                verbose_name="전화번호",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="representative",
            field=models.CharField(
                default="-", max_length=100, verbose_name="대표자명"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(verbose_name="주소"),
        ),
    ]
