# Generated by Django 5.2.11 on 2026-02-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0020_remove_company_region_company_business_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="business_category",
        ),
        migrations.RemoveField(
            model_name="company",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
    ]
