# Generated by Django 5.2.11 on 2026-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0021_remove_company_business_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="part_type",
            field=models.CharField(
                choices=[("part", "부품"), ("labor", "공임")],
                default="part",
                max_length=10,
                verbose_name="구분",
            ),
        ),
    ]
