# Generated by Django 5.2.11 on 2026-03-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0022_part_part_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImprovementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "content",
                    models.TextField(
                        help_text="개선을 원하는 내용을 자세히 작성해 주세요.",
                        verbose_name="내용",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "접수"),
                            ("IN_PROGRESS", "검토 중"),
                            ("COMPLETED", "반영 완료"),
                            ("REJECTED", "반려"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="관리자가 작성하는 답변/처리 결과",
                        verbose_name="관리자 답변",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "개선사항 요청",
                "verbose_name_plural": "개선사항 요청",
                "ordering": ["-created_at"],
            },
        ),
    ]
