# Generated by Django 5.2.11 on 2026-03-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0023_improvementrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="그룹 단가"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="as_app.companycategory",
                        verbose_name="단가 그룹",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_prices",
                        to="as_app.part",
                        verbose_name="부품",
                    ),
                ),
            ],
            options={
                "verbose_name": "단가 그룹별 금액",
                "verbose_name_plural": "단가 그룹별 금액",
                "unique_together": {("part", "category")},
            },
        ),
    ]
