# Generated by Django 5.2.11 on 2026-03-03 21:15

from django.db import migrations


def migrate_part_prices(apps, schema_editor):
    Part = apps.get_model("as_app", "Part")
    CompanyCategory = apps.get_model("as_app", "CompanyCategory")
    PartPrice = apps.get_model("as_app", "PartPrice")

    # Ensure "다스" category exists
    das_category, created = CompanyCategory.objects.get_or_create(name="다스")

    # Migrate all part base prices to "다스" PartPrice
    part_prices_to_create = []
    for part in Part.objects.all():
        part_prices_to_create.append(
            PartPrice(part=part, category=das_category, price=part.price)
        )
    
    if part_prices_to_create:
        PartPrice.objects.bulk_create(part_prices_to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0024_partprice"),
    ]

    operations = [
        migrations.RunPython(migrate_part_prices, migrations.RunPython.noop),
    ]
