# Generated by Django 5.2.11 on 2026-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0025_migrate_part_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="price",
        ),
    ]
