# Generated by Django 5.2.11 on 2026-03-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0027_move_master_data"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asticket",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="master_data.company",
                verbose_name="매출처",
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="outsource_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="master_data.outsourcecompany",
                verbose_name="의뢰업체",
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="master_data.tool",
                verbose_name="장비/툴",
            ),
        ),
        migrations.AlterField(
            model_name="inboundbatch",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_batches",
                to="master_data.company",
                verbose_name="매출처",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts",
                to="master_data.brand",
                verbose_name="브랜드",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="이 부품이 사용되는 장비를 선택하세요. 공용 부품은 여러 장비를 선택할 수 있습니다.",
                related_name="parts",
                to="master_data.tool",
                verbose_name="적용 장비/툴",
            ),
        ),
        migrations.AlterField(
            model_name="partprice",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.companycategory",
                verbose_name="단가 그룹",
            ),
        ),
        migrations.AlterField(
            model_name="repairpreset",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repair_presets",
                to="master_data.brand",
                verbose_name="브랜드",
            ),
        ),
        migrations.AlterField(
            model_name="repairpreset",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="이 세트가 적용되는 장비를 선택하세요. 비워두면 모든 장비에 표시됩니다.",
                related_name="repair_presets",
                to="master_data.tool",
                verbose_name="적용 장비/툴",
            ),
        ),
    ]
