# Generated by Django 5.2.11 on 2026-03-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0028_alter_asticket_company_and_more"),
    ]

    operations = []
