# Generated by Django 5.2.11 on 2026-03-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0029_remove_tool_refs"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutsourcedTicket",
            fields=[],
            options={
                "verbose_name": "수리의뢰 현황",
                "verbose_name_plural": "수리의뢰 현황",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.AddField(
            model_name="asticket",
            name="outsource_date",
            field=models.DateField(blank=True, null=True, verbose_name="의뢰 날짜"),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "입고"),
                    ("outsourced", "수리의뢰"),
                    ("repaired", "수리완료"),
                    ("shipped", "출고"),
                    ("disposed", "자체폐기"),
                ],
                default="inbound",
                max_length=15,
                verbose_name="상태",
            ),
        ),
    ]
