# Generated by Django 5.2.11 on 2026-03-17 03:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0030_outsourcedticket_asticket_outsource_date_and_more"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPart",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        choices=[("part", "부품"), ("labor", "공임")],
                        default="part",
                        max_length=10,
                        verbose_name="구분",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="부품명")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="부품코드"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="비고")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="master_data.brand",
                        verbose_name="브랜드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 수리부품",
                "verbose_name_plural": "historical 수리부품 관리",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TicketUsedPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applied_price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="수리 완료 시점의 마스터 부품 단가 (스냅샷)",
                        verbose_name="적용 단가",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="as_app.part",
                        verbose_name="부품",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_used_parts",
                        to="as_app.asticket",
                        verbose_name="AS 티켓",
                    ),
                ),
            ],
            options={
                "verbose_name": "수리 사용 부품 (스냅샷)",
                "verbose_name_plural": "수리 사용 부품 (스냅샷)",
                "ordering": ["id"],
            },
        ),
    ]
