# Generated by Django 5.2.11 on 2026-03-17 03:03

from django.db import migrations

def migrate_used_parts(apps, schema_editor):
    ASTicket = apps.get_model("as_app", "ASTicket")
    TicketUsedPart = apps.get_model("as_app", "TicketUsedPart")
    PartPrice = apps.get_model("as_app", "PartPrice")
    CompanyCategory = apps.get_model("master_data", "CompanyCategory")

    try:
        das_category = CompanyCategory.objects.get(name="다스")
    except CompanyCategory.DoesNotExist:
        das_category = None

    for ticket in ASTicket.objects.all():
        company = getattr(ticket, "company", None)
        price_group = getattr(company, "price_group", None) if company else None

        for part in ticket.used_parts.all():
            price = 0
            if price_group:
                group_price = PartPrice.objects.filter(part=part, category=price_group).first()
                if group_price:
                    price = group_price.price
            
            if price == 0 and das_category:
                default_group = PartPrice.objects.filter(part=part, category=das_category).first()
                if default_group:
                    price = default_group.price
            
            TicketUsedPart.objects.create(
                ticket=ticket,
                part=part,
                applied_price=price
            )

def reverse_migrate_used_parts(apps, schema_editor):
    TicketUsedPart = apps.get_model("as_app", "TicketUsedPart")
    TicketUsedPart.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0031_historicalpart_ticketusedpart"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_used_parts, reverse_migrate_used_parts),
    ]
