# Generated by Django 5.2.11 on 2026-03-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0032_data_migrate_used_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asticket",
            name="used_parts",
        ),
        migrations.AddField(
            model_name="asticket",
            name="used_parts",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets",
                through="as_app.TicketUsedPart",
                to="as_app.part",
                verbose_name="사용 부품/공임",
            ),
        ),
    ]
