# Generated by Django 5.2.11 on 2026-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_app", "0033_alter_asticket_used_parts"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldTicket",
            fields=[],
            options={
                "verbose_name": "수리보류 등록",
                "verbose_name_plural": "수리보류 등록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("as_app.asticket",),
        ),
        migrations.AddField(
            model_name="asticket",
            name="hold_date",
            field=models.DateField(
                blank=True,
                help_text="수리보류 상태로 변경된 날짜 (자동 기록)",
                null=True,
                verbose_name="보류 처리일",
            ),
        ),
        migrations.AlterField(
            model_name="asticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbound", "입고"),
                    ("outsourced", "수리의뢰"),
                    ("repaired", "수리완료"),
                    ("shipped", "출고"),
                    ("disposed", "자체폐기"),
                    ("hold", "수리보류"),
                ],
                default="inbound",
                max_length=15,
                verbose_name="상태",
            ),
        ),
    ]
